<?php
/**
 * @author       bangujo ON 2021-04-17 09:10
 * @project      elolara
 * @ide          PhpStorm
 * @originalFile ElolaraServiceProvider.php
 */

namespace Angujo\Elolara\Laravel;


use Illuminate\Foundation\Application;
use Angujo\Elolara\Laravel\Factory as Elolara;
use Illuminate\Support\ServiceProvider;

/**
 * Class ElolaraServiceProvider
 *
 * @package Angujo\Elolara\Laravel
 */
class ElolaraServiceProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        $this->app->singleton(Elolara::class, function(){
            return new Elolara();
        });
    }

    public function boot()
    {
        if ($this->app->runningInConsole()) {
            $this->commands([ModelCommand::class]);
        }
        $this->publishes([__DIR__.DIRECTORY_SEPARATOR.'config.php' => config_path(LM_APP_NAME.'.php')]);
    }
}