<?php
/**
 * @author       bangujo ON 2021-04-17 09:10
 * @project      laravelmodel
 * @ide          PhpStorm
 * @originalFile LaravelModelServiceProvider.php
 */

namespace Angujo\LaravelModel\Laravel;


use Angujo\LaravelModel\Config;
use Illuminate\Foundation\Application;
use Angujo\LaravelModel\Laravel\Factory as LaravelModel;

/**
 * Class LaravelModelServiceProvider
 *
 * @package Angujo\LaravelModel\Laravel
 */
class LaravelModelServiceProvider extends \Illuminate\Support\ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        $this->app->singleton(LaravelModel::class, function(Application $app){
            return new LaravelModel();
        });
    }

    public function boot()
    {
        if ($this->app->runningInConsole()) {
            $this->commands([ModelCommand::class]);
        }
        $this->publishes([__DIR__.DIRECTORY_SEPARATOR.'config.php' => config_path(Config::CONFIG_NAME.'.php')]);
    }
}